packages:
  # all packages in direct subdirs of packages/
  # - 'packages/*'
  # all packages in direct subdirs of packages/
  - 'projects/*'
  # all packages in subdirs of components/
  # - 'packages/components/**'
  # api base axios request
  # - 'packages/api/**'
  # all util in subdirs
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'